### ISSUE TITLE
SeparatedButtons: Provide option of not showing separator at line breaks

### ISSUE THREAD

**Issue by MarcelGarus** [JonasWanke/black_hole_flutter#10]
Currently, if the buttons wrap over multiple lines, a separator is shown right before/after a line break. It would be nice to have the option to omit the separator in that case.

For example, here's a design I'm struggling to implement using this package:

![image](https://user-images.githubusercontent.com/8601189/170688700-d0ced355-f3fa-4e0a-8f29-412db30254f0.png)

**Comment by JonasWanke** [comment]
Closing this since `SeparatedButtons` got removed in version 1.0.0: https://pub.dev/packages/black_hole_flutter/changelog#100--2023-01-24
