### ISSUE TITLE
Error: A constant constructor can't call a non-constant super constructor.

### ISSUE THREAD

**Issue by MarceloEsser** [JonasWanke/black_hole_flutter#16]
Hi! the project just don't run. To replicate you need to try to run the project.
Here a snapshot of the occurence

../../../../../.pub-cache/hosted/pub.dev/black_hole_flutter-1.0.2/lib/src/widgets/fill_or_wrap.dart:20:9: Error: A constant constructor can't call a non-constant super constructor.
  const FillOrWrap({
        ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

**Environment:**

- OS version: N
- Flutter version: 3.7.9
- Package version:  1.0.2

**Comment by JonasWanke** [comment]
Sorry, it looks like the parent class's constructor was only made `const` around Flutter 3.10. I removed the `const` modifier in [v1.0.3](https://pub.dev/packages/black_hole_flutter/changelog#103--2023-05-11) to support older Flutter versions

**Comment by MarceloEsser** [comment]
> Sorry, it looks like the parent class's constructor was only made `const` around Flutter 3.10. I removed the `const` modifier in [v1.0.3](https://pub.dev/packages/black_hole_flutter/changelog#103--2023-05-11) to support older Flutter versions

No problem, I tried to open a pull requet but obviously I have no permissions to do that. Probably this change will broke another projects too. Anyway... thanks for fast suport 😎. Best regards!
