### ISSUE TITLE
Add controller property to ExpandOrScroll widget

### ISSUE THREAD

**Issue by MarcelGarus** [JonasWanke/black_hole_flutter#8]
I want to customize the `ScrollController` that the `ExpandOrScroll` uses internally.

**Comment by JonasWanke** [comment]
Added in [`69deb46`](https://github.com/JonasWanke/black_hole_flutter/commit/69deb466d1b1125ed005d691518e85479ec764d6) and published in [v0.3.4](https://pub.dev/packages/black_hole_flutter/changelog#034--2021-12-04)
