### ISSUE TITLE
SeparatedButtons: Support using a custom widget as the separator

### ISSUE THREAD

**Issue by MarcelGarus** [JonasWanke/black_hole_flutter#9]
Currently, it's hardcoded to a Unicode dot. Is it possible to customize this to a completely custom widget?

For example, I might want to show a custom line with a different-than-default color:

![image](https://user-images.githubusercontent.com/8601189/170688877-cd33679d-4d65-4c68-b270-7ae70dd6735e.png)

**Comment by JonasWanke** [comment]
Closing this since `SeparatedButtons` got removed in version 1.0.0: https://pub.dev/packages/black_hole_flutter/changelog#100--2023-01-24
